// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMULCa5c3NpVR6ENbTakAvnmVmFwbyas',
    appId: '1:841452398876:web:13636ac6e6a7fc05be72d9',
    messagingSenderId: '841452398876',
    projectId: 'timeflow-5b4e6',
    authDomain: 'timeflow-5b4e6.firebaseapp.com',
    storageBucket: 'timeflow-5b4e6.firebasestorage.app',
    measurementId: 'G-0MSGS3G4PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxFnoTQa8DYYHF_UH3vp0aTmELM5Hg64',
    appId: '1:841452398876:android:b79fe744e59862a8be72d9',
    messagingSenderId: '841452398876',
    projectId: 'timeflow-5b4e6',
    storageBucket: 'timeflow-5b4e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRLsz31F8EdS84dlDgLHlpNfuE2uyQPkw',
    appId: '1:841452398876:ios:1d10ac9d129e4f58be72d9',
    messagingSenderId: '841452398876',
    projectId: 'timeflow-5b4e6',
    storageBucket: 'timeflow-5b4e6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAppdeponto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRLsz31F8EdS84dlDgLHlpNfuE2uyQPkw',
    appId: '1:841452398876:ios:1d10ac9d129e4f58be72d9',
    messagingSenderId: '841452398876',
    projectId: 'timeflow-5b4e6',
    storageBucket: 'timeflow-5b4e6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAppdeponto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMULCa5c3NpVR6ENbTakAvnmVmFwbyas',
    appId: '1:841452398876:web:229cad57978f18bdbe72d9',
    messagingSenderId: '841452398876',
    projectId: 'timeflow-5b4e6',
    authDomain: 'timeflow-5b4e6.firebaseapp.com',
    storageBucket: 'timeflow-5b4e6.firebasestorage.app',
    measurementId: 'G-VWBSVKJ7BP',
  );
}
